// leetcode - 389
/*
 You are given two strings s and t.

String t is generated by random shuffling string s 
and then add one more letter at a random position.

Return the letter that was added to t.

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 */
package Strings;

public class Find_The_Difference 
{
	public static void main(String[] args) 
	{
		String s="abcd";
		String t="abcde";
		int sum=0;   // ASCII table small a will start from 97 .
		for(char c:t.toCharArray())
			sum+=c;
		for(char c:s.toCharArray())
			sum-=c;
		System.out.println((char)sum);
	}
}
